imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ['%locale%'] }
    secret:          '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:
        enabled: true
        #enable_annotations: true
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  '%locale%'
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Assetic Configuration
assetic:
    debug:          '%kernel.debug%'
    use_controller: false
    bundles:        [CmfCreateBundle, AppBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
    assets:
        font_awesome:
            inputs: '@AppBundle/Resources/public/css/font-awesome-4.6.3/css/font-awesome.min.css'
            output: 'css/font-awesome.css'
        font_awesome_otf:
            inputs: '@AppBundle/Resources/public/css/font-awesome-4.6.3/fonts/FontAwesome.otf'
            output: 'fonts/FontAwesome.otf'
        font_awesome_woff:
            inputs: '@AppBundle/Resources/public/css/font-awesome-4.6.3/fonts/fontawesome-webfont.woff'
            output: 'fonts/FontAwesome.woff'
        font_awesome_woff2:
            inputs: '@AppBundle/Resources/public/css/font-awesome-4.6.3/fonts/fontawesome-webfont.woff2'
            output: 'fonts/FontAwesome.woff2'
        font_awesome_eot:
            inputs: '@AppBundle/Resources/public/css/font-awesome-4.6.3/fonts/fontawesome-webfont.eot'
            output: 'fonts/fontawesome-webfont.eot'
        font_awesome_svg:
            inputs: '@AppBundle/Resources/public/css/font-awesome-4.6.3/fonts/fontawesome-webfont.svg'
            output: 'fonts/fontawesome-webfont.svg'
        font_awesome_ttf:
            inputs: '@AppBundle/Resources/public/css/font-awesome-4.6.3/fonts/fontawesome-webfont.ttf'
            output: 'fonts/fontawesome-webfont.ttf'
        #closure:
        #    jar: '%kernel.root_dir%/Resources/java/compiler.jar'
        #yui_css:
        #    jar: '%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar'

# Doctrine Configuration (needed for Jackalope Doctrine DBAL)
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     '%database_host%'
        port:     '%database_port%'
        dbname:   '%database_name%'
        user:     '%database_user%'
        password: '%database_password%'
        charset:  UTF8
        path:     '%database_path%'
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    AppBundle:
                        type: "annotation"
                        dir: "Entity"
                        prefix: 'AppBundle\Entity'
# Doctrine PHPCR-ODM configuration
doctrine_phpcr:
    session:
        backend:   '%phpcr_backend%'
        workspace: '%phpcr_workspace%'
        username:  '%phpcr_user%'
        password:  '%phpcr_password%'
    odm:
        auto_mapping: true
        auto_generate_proxy_classes: '%kernel.debug%'

# Jackalope Metadata and Node Cache services
doctrine_cache:
    providers:
        phpcr_meta:
            type: file_system
        phpcr_nodes:
            type: file_system

# Main Cmf Configuration
cmf_core:
    persistence:
        phpcr: true
        # if you want another basepath
        # basepath: /custom/basepath
    publish_workflow: false

# Cmf Routing Configuration
cmf_routing:
    dynamic:
        templates_by_class:
            Symfony\Cmf\Bundle\SimpleCmsBundle\Doctrine\Phpcr\Page: 'page/index.html.twig'
            Symfony\Cmf\Bundle\ContentBundle\Doctrine\Phpcr\StaticContent: 'page/index.html.twig'
        controllers_by_class:
            AppBundle\Document\Page: AppBundle\Controller\DefaultController::pageAction

# Menu Configuration
#knp_menu:
#    twig: true

# Block Configuration
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata_admin_doctrine_phpcr.tree_block:
            settings:
                id: '/cms'
            contexts: [admin]
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]
sonata_admin:
    dashboard:
        blocks:
            - { position: left, type: sonata_admin_doctrine_phpcr.tree_block }
            - { position: right, type: sonata.admin.block.admin_list }
sonata_doctrine_phpcr_admin:
    document_tree:
        Doctrine\ODM\PHPCR\Document\Generic:
            valid_children:
                - all
        # if you are using the SimpleCmsBundle, enable the Page as well
        # Symfony\Cmf\Bundle\SimpleCmsBundle\Doctrine\Phpcr\Page:
        #     valid_children:
        #         - all
        Symfony\Cmf\Bundle\ContentBundle\Doctrine\Phpcr\StaticContent:
            valid_children:
                - all
        Symfony\Cmf\Bundle\RoutingBundle\Doctrine\Phpcr\Route:
            valid_children:
                - Symfony\Cmf\Bundle\RoutingBundle\Doctrine\Phpcr\Route
                - Symfony\Cmf\Bundle\RoutingBundle\Doctrine\Phpcr\RedirectRoute
        Symfony\Cmf\Bundle\RoutingBundle\Doctrine\Phpcr\RedirectRoute:
            valid_children: []
        Symfony\Cmf\Bundle\MenuBundle\Doctrine\Phpcr\MenuNode:
            valid_children:
                - Symfony\Cmf\Bundle\MenuBundle\Doctrine\Phpcr\MenuNode
# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host:      '%mailer_host%'
    username:  '%mailer_user%'
    password:  '%mailer_password%'
    spool:     { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: AppBundle\Entity\User
cmf_routing:
    chain:
        routers_by_id:
            cmf_routing.dynamic_router: 20
            router.default: 100
    dynamic:
        persistence:
            phpcr:
                enabled: true
                use_sonata_admin: auto
                content_basepath: ~
        generic_controller: cmf_content.controller:indexAction
        controllers_by_type:
            editable_static: sandbox_main.controller:indexAction
        controllers_by_class:
            Symfony\Cmf\Bundle\ContentBundle\Document\StaticContent: cmf_content.controller::indexAction
        templates_by_class:
            Symfony\Cmf\Bundle\ContentBundle\Document\StaticContent: CmfContentBundle:StaticContent:index.html.twig
knp_menu:
    twig: true